# Generated by Django 5.0.4 on 2026-01-28 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0005_purchase_movie_is_premium'),
    ]

    operations = [
        migrations.CreateModel(
            name='IshTuri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ish_turi', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AsosiyIsh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ish_nomi', models.CharField(max_length=100)),
                ('ish_soati', models.IntegerField()),
                ('ish_turi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.ishturi')),
            ],
        ),
    ]
